# sushy-tools emulator configuration
# Python file — values are Python literals.

SUSHY_EMULATOR_LISTEN_IP = u'0.0.0.0'
SUSHY_EMULATOR_LISTEN_PORT = 8000
SUSHY_EMULATOR_LIBVIRT_URI = u'qemu:///system'
SUSHY_EMULATOR_SSL_CERT = None
SUSHY_EMULATOR_SSL_KEY  = None
SUSHY_EMULATOR_AUTH_FILE = None
