#!/usr/bin/env bash
# create-vms.sh — create libvirt VMs on the DGX Spark
#
# Creates VMs with:
#   - UEFI boot (AAVMF, no secure boot)
#   - PXE-first boot order
#   - Attached to br-provision
#
# Writes VM inventory to configs/vm-inventory.txt

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PROVISION_BRIDGE="${PROVISION_BRIDGE:-br-provision}"
PROVISION_IP="${PROVISION_IP:-192.168.1.101}"
SUSHY_PORT="${SUSHY_PORT:-8000}"

SMALL_VM_COUNT="${SMALL_VM_COUNT:-3}"
SMALL_VM_VCPUS="${SMALL_VM_VCPUS:-2}"
SMALL_VM_RAM_MB="${SMALL_VM_RAM_MB:-4096}"
SMALL_VM_DISK_GB="${SMALL_VM_DISK_GB:-40}"
SMALL_VM_NAME_PREFIX="${SMALL_VM_NAME_PREFIX:-vmetal-small}"

LARGE_VM_COUNT="${LARGE_VM_COUNT:-2}"
LARGE_VM_VCPUS="${LARGE_VM_VCPUS:-4}"
LARGE_VM_RAM_MB="${LARGE_VM_RAM_MB:-8192}"
LARGE_VM_DISK_GB="${LARGE_VM_DISK_GB:-80}"
LARGE_VM_NAME_PREFIX="${LARGE_VM_NAME_PREFIX:-vmetal-large}"

VM_IMAGE_DIR="${VM_IMAGE_DIR:-/var/lib/libvirt/images}"

[[ -f "${REPO_ROOT}/.env" ]] && source "${REPO_ROOT}/.env"

INVENTORY_FILE="${REPO_ROOT}/configs/vm-inventory.txt"

log() { echo "[create-vms] $*"; }

gen_mac() {
  local profile="$1" index="$2"
  local hi lo
  hi=$(printf '%02x' $(( (index - 1) / 256 )))
  lo=$(printf '%02x' $(( (index - 1) % 256 )))
  echo "52:54:00:${profile}:${hi}:${lo}"
}

create_vm() {
  local name="$1" vcpus="$2" ram_mb="$3" disk_gb="$4" mac="$5"
  local disk_path="${VM_IMAGE_DIR}/${name}.qcow2"

  if sudo virsh dominfo "${name}" &>/dev/null; then
    log "Domain '${name}' already exists — skipping"
    return 0
  fi

  log "Creating VM: ${name} (${vcpus} vCPU, ${ram_mb} MB, ${disk_gb} GB, MAC ${mac})"

  if [[ ! -f "${disk_path}" ]]; then
    sudo qemu-img create -f qcow2 "${disk_path}" "${disk_gb}G"
  fi

  sudo virt-install \
    --name "${name}" \
    --vcpus "${vcpus}" \
    --memory "${ram_mb}" \
    --disk "path=${disk_path},format=qcow2,bus=virtio" \
    --network "bridge:${PROVISION_BRIDGE},model=virtio,mac=${mac}" \
    --boot "network,hd,menu=off" \
    --os-variant "ubuntu24.04" \
    --graphics "none" \
    --console "pty,target_type=serial" \
    --noautoconsole \
    --import \
    --noreboot

  # Disable secure boot — AAVMF defaults have it enabled, IPA ramdisk is unsigned
  log "Disabling secure boot on ${name}..."
  local xmlfile="/tmp/${name}-nosecboot.xml"
  sudo virsh dumpxml "${name}" > "${xmlfile}"
  sed -i "/<firmware>/,/<\/firmware>/d" "${xmlfile}"
  sed -i "s|AAVMF_CODE.ms.fd|AAVMF_CODE.no-secboot.fd|" "${xmlfile}"
  sed -i "s|AAVMF_VARS.ms.fd|AAVMF_VARS.fd|" "${xmlfile}"
  sudo rm -f "/var/lib/libvirt/qemu/nvram/${name}_VARS.fd"
  sudo virsh define "${xmlfile}"
  rm -f "${xmlfile}"

  log "VM '${name}' defined (no secure boot)."
}

# ---------------------------------------------------------------------------
# Create VMs
# ---------------------------------------------------------------------------
log "=== Creating ${SMALL_VM_COUNT} small VMs ==="
for i in $(seq 1 "${SMALL_VM_COUNT}"); do
  create_vm "${SMALL_VM_NAME_PREFIX}-${i}" "${SMALL_VM_VCPUS}" "${SMALL_VM_RAM_MB}" "${SMALL_VM_DISK_GB}" "$(gen_mac aa "${i}")"
done

log "=== Creating ${LARGE_VM_COUNT} large VMs ==="
for i in $(seq 1 "${LARGE_VM_COUNT}"); do
  create_vm "${LARGE_VM_NAME_PREFIX}-${i}" "${LARGE_VM_VCPUS}" "${LARGE_VM_RAM_MB}" "${LARGE_VM_DISK_GB}" "$(gen_mac bb "${i}")"
done

# ---------------------------------------------------------------------------
# Write inventory
# ---------------------------------------------------------------------------
log "Writing VM inventory..."
cat > "${INVENTORY_FILE}" <<'EOF'
# vmetal-dgxspark-demo VM inventory
# Auto-generated by create-vms.sh — do not edit manually.
# Format: NAME UUID MAC PROFILE
EOF

for i in $(seq 1 "${SMALL_VM_COUNT}"); do
  vm_name="${SMALL_VM_NAME_PREFIX}-${i}"
  mac=$(gen_mac "aa" "${i}")
  uuid=$(sudo virsh dominfo "${vm_name}" 2>/dev/null | awk '/^UUID/{print $2}')
  echo "${vm_name} ${uuid} ${mac} small" >> "${INVENTORY_FILE}"
done

for i in $(seq 1 "${LARGE_VM_COUNT}"); do
  vm_name="${LARGE_VM_NAME_PREFIX}-${i}"
  mac=$(gen_mac "bb" "${i}")
  uuid=$(sudo virsh dominfo "${vm_name}" 2>/dev/null | awk '/^UUID/{print $2}')
  echo "${vm_name} ${uuid} ${mac} large" >> "${INVENTORY_FILE}"
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "====================================================================="
printf "%-22s %-38s %-19s %-8s\n" "NAME" "UUID" "MAC" "PROFILE"
echo "---------------------------------------------------------------------"
while read -r line; do
  [[ "${line}" =~ ^#.*$ || -z "${line}" ]] && continue
  read -r name uuid mac profile <<< "${line}"
  printf "%-22s %-38s %-19s %-8s\n" "${name}" "${uuid}" "${mac}" "${profile}"
done < "${INVENTORY_FILE}"
echo "====================================================================="
echo ""
echo "Inventory: ${INVENTORY_FILE}"
echo "Next: bash scripts/install-sushy-service.sh"
